server:
  port: 8765
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: Microservice1
          uri: http://localhost:8081/
          predicates:
            - Path=/serviceB/**
        - id: Microservice2
          uri: http://localhost:8082/
          predicates:
            - Path=/serviceA/**