spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks_hw5
    username: tasks_hw5
    password: tasks_hw5
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop

  management:
    endpoints:
      web:
        exposure:
          include: metrics, prometheus




